[package]
name = "aoc-2022"
version = "0.1.0"
edition = "2021"
authors = ["Tom LeGodais <tomlegodais@gmail.com>"]

[lib]
name = "aoc"

[dependencies]
anyhow = "1.0.66"
spectral = "0.6.0"
itertools = "0.10.5"
once_cell = "1.16.0"
regex = { version = "1.7.0", features = ["pattern"] }