[package]
name = "aoc-2022"
version = "0.1.0"
edition = "2021"
authors = ["Tom LeGodais <tomlegodais@gmail.com>"]

[dependencies]
anyhow = "1.0.66"
spectral = "0.6.0"
itertools = "0.10.5"

[lib]
name = "aoc"